name: Test service on main

on:
  pull_request:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  build:
    runs-on: ["self-hosted", "main"]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.SHARED_PAT }}
          submodules: recursive
      - name: Rebuild Compose Images
        run: docker compose -f docker-compose.test.yml build --no-cache
      - name: Test image with Docker Compose
        run: docker compose -f docker-compose.test.yml up --force-recreate --abort-on-container-exit --exit-code-from app
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: arilith/r_ov
          registry: docker.io
          tags: gtfsrt
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  compose-down:
    runs-on: ["self-hosted", "main"]
    if: ${{ always() }}
    needs: [build]
    steps:
      - name: Docker compose down
        run: docker compose -f docker-compose.test.yml down